assistant/orders/urls.py
from django.urls import path

from .views import OrderListView, order_search, add_to_purchase_modal

app_name = "orders"

urlpatterns = [
    path("", OrderListView.as_view(), name="order-list"),
    path('search/', order_search, name="order-search"),
    path(
        "add-to-purchase-modal/<uuid:guid>/",
        add_to_purchase_modal,
        name="add_to_purchase_modal",
    ),
]

assistant/weblink_channel/urls.py
from django.urls import path

from .views import (
    get_product_by_link,
    get_product_by_link_sync,
    checkout,
    CustomerOrderList,
    CustomerOrderDetail,
    CustomerOrderCreate,
    CustomerProductVariantListView,
    CustomerProductVariantDetailView,
    checkout_api_view,
)

app_name = "weblink_channel"

urlpatterns = [
    path("scrape/", get_product_by_link, name="get_product_by_link"),
    path("sync-scrape/", get_product_by_link_sync, name="get_product_by_link_sync",),
    path("checkout/", checkout, name="checkout"),
    path("checkout-api/", checkout_api_view, name="checkout-api-view"),
    path("guest-checkout-api/", checkout_api_view, name="guest-checkout-api-view"),
    path("customer-orders/", CustomerOrderList.as_view(), name="customer_order_list"),
    path(
        "customer-orders/<uuid:guid>/",
        CustomerOrderDetail.as_view(),
        name="customer_order_detail",
    ),
    path(
        "customer-orders/new/",
        CustomerOrderCreate.as_view(),
        name="customer_order_create",
    ),
    path(
        "customer-products/",
        CustomerProductVariantListView.as_view(),
        name="customer_product_list",
    ),
    path(
        "customer-products/<uuid:guid>/",
        CustomerProductVariantDetailView.as_view(),
        name="customer_product_detail",
    ),
]

config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.urls import include, path
from django.views import defaults as default_views
from django.views.generic import TemplateView
from rest_framework.authtoken.views import obtain_auth_token

from wagtail.core import urls as wagtail_urls
from wagtail.admin import urls as wagtailadmin_urls
from wagtail.documents import urls as wagtaildocs_urls

urlpatterns = [
    # Django Admin, use {% url 'admin:index' %}
    path(settings.ADMIN_URL, admin.site.urls),
    # User management
    path("users/", include("assistant.users.urls", namespace="users")),
    path("ht/", include("health_check.urls")),
    path("accounts/", include("allauth.urls")),
    # Wagtail Admin
    path("cms/", include(wagtailadmin_urls)),
    path("documents/", include(wagtaildocs_urls)),
    # Your stuff: custom urls includes go here
    path("pages/", include("assistant.pages.urls", namespace="pages")),
    path("products/", include("assistant.products.urls", namespace="products")),
    path("purchases/", include("assistant.purchases.urls", namespace="purchases")),
    path("orders/", include("assistant.orders.urls", namespace="orders")),
    path("warehouse/", include("assistant.warehouse.urls", namespace="warehouse")),
    path("shipping/", include("assistant.shipping.urls", namespace="shipping")),
    path(
        "weblink-channel/",
        include("assistant.weblink_channel.urls", namespace="weblink_channel"),
    ),
    path("shopify/", include("assistant.shopify_sync.urls"), name="shopify_sync"),
    path("api/", include("config.api_router")),
    path("auth-token/", obtain_auth_token),
    # Wagtail CMS
    path("", include(wagtail_urls)),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
if settings.DEBUG:
    # Static file serving when using Gunicorn + Uvicorn for local web socket development
    urlpatterns += staticfiles_urlpatterns()

# API URLS
# urlpatterns += [
#     # API base url
#     path("api/", include("config.api_router")),
#     # DRF auth token
#     path("auth-token/", obtain_auth_token),
#     # Wagtail CMS
#     path('', include(wagtail_urls)),
# ]

if settings.USE_SILK:
    urlpatterns += [path("silk/", include("silk.urls", namespace="silk"))]

if settings.DEBUG:
    # This allows the error pages to be debugged during development, just visit
    # these url in browser to see how these error pages look like.
    urlpatterns += [
        path(
            "400/",
            default_views.bad_request,
            kwargs={"exception": Exception("Bad Request!")},
        ),
        path(
            "403/",
            default_views.permission_denied,
            kwargs={"exception": Exception("Permission Denied")},
        ),
        path(
            "404/",
            default_views.page_not_found,
            kwargs={"exception": Exception("Page not Found")},
        ),
        path("500/", default_views.server_error),
    ]
    if "debug_toolbar" in settings.INSTALLED_APPS:
        import debug_toolbar

        urlpatterns = [path("__debug__/", include(debug_toolbar.urls))] + urlpatterns

assistant/orders/models.py
from re import match

from django.conf import settings
from django.core.exceptions import ValidationError
from django.core.validators import MinValueValidator
from django.db import models
from django.db.models import Max, Sum
from django.utils.translation import gettext_lazy as _
from django_measurement.models import MeasurementField
from measurement.measures import Weight
from modelcluster.fields import ParentalKey
from modelcluster.models import ClusterableModel
from sequences import get_next_value
from wagtail.contrib.table_block.blocks import TableBlock
from wagtail.core.blocks import StreamBlock
from wagtail.core.fields import StreamField
from wagtail.core.models import Orderable
from wagtail.search import index

from assistant.core.models import BaseModel


class WeightUnits:
    KILOGRAM = "kg"
    POUND = "lb"
    OUNCE = "oz"
    GRAM = "g"

    CHOICES = [
        (KILOGRAM, "kg"),
        (POUND, "lb"),
        (OUNCE, "oz"),
        (GRAM, "g"),
    ]


def zero_weight():
    """Represent the zero weight value."""
    return Weight(kg=0)


class Order(index.Indexed, BaseModel, ClusterableModel):
    """The Orders model records all orders placed through the online store system
    by customers, as well as those created manually by administrators. 
    An order is created by syncing with an online e-commerce system.
    """

    class OrderType(models.TextChoices):
        REGULAR = "regular", _("Orders by customers")
        DRAFT = "draft", _("Created by staff, Not confirmed")

    class StatusChoices(models.TextChoices):
        # fully editable, not confirmed order created by staff users
        DRAFT = "draft", _("Draft")
        # order with no items marked as fulfilled
        UNFULFILLED = "unfulfilled", _("Unfulfilled")
        # order with some items marked as fulfilled
        PARTIALLY_FULFILLED = "partially_fulfilled", _("Partially Fulfilled")
        # order with all items marked as fulfilled
        FULFILLED = "fulfilled", _("Fulfilled")
        # permanently canceled order
        CANCELED = "canceled", _("Canceled")

    class FinancialStatusChoices(models.TextChoices):
        # Show only authorized orders
        AUTHORIZED = "authorized", _("Authorized")
        # Show only pending orders
        PENDING = "pending", _("Pending")
        # Show only paid orders
        PAID = "paid", _("Paid")
        # Show only partially paid orders
        PARTIALLY_PAID = "partially_paid", _("Partially Paid")
        # Show only refunded orders
        REFUNDED = "refunded", _("Refunded")
        # Show only voided orders
        VOIDED = "voided", _("Voided")
        # Show only partially refunded orders
        PARTIALLY_REFUNDED = "partially_refunded", _("Partially Refunded")
        # Show orders of any financial status.
        ANY = "any", _("Any")
        # Show authorized and partially paid orders.
        UNPAID = "unpaid", _("Unpaid")

    class CancelReasonChoices(models.TextChoices):

        CUSTOMER = "customer", _("Customer")
        FRAUD = "fraud", _("Fraud")
        INVENTORY = "inventory", _("Inventory")
        DECLINED = "declined", _("Declined")
        OTHER = "other", _("Other")

    number = models.CharField(
        verbose_name=_("Order Number"),
        max_length=255,
        unique=True,
        help_text=_(
            "The order 's position in the shop's count of orders starting at 1001. "
            "Order numbers are sequential and start at 1001."
        ),
    )
    customer_email = models.EmailField(blank=True, default="")
    customer_id = models.CharField(max_length=255, blank=True, null=True)

    total_price = models.DecimalField(
        max_digits=10,
        decimal_places=2,
        help_text=_(
            "The sum of all line item prices, discounts, shipping, taxes, and tips in the shop currency. "
            "Must be positive."
        ),
    )
    subtotal_price = models.DecimalField(
        max_digits=10,
        decimal_places=2,
        null=True,
        help_text=_(
            "The price of the order in the shop currency after discounts but before shipping, taxes, and tips."
        ),
    )
    total_tax = models.DecimalField(
        max_digits=10,
        decimal_places=2,
        null=True,
        help_text=_(
            "The sum of all the taxes applied to the order in th shop currency. Must be positive."
        ),
    )

    weight = MeasurementField(
        measurement=Weight, unit_choices=WeightUnits.CHOICES, default=zero_weight,
    )

    status = models.CharField(
        max_length=32, default=StatusChoices.UNFULFILLED, choices=StatusChoices.choices,
    )
    financial_status = models.CharField(
        verbose_name=_("Financial Status"),
        max_length=100,
        default=FinancialStatusChoices.UNPAID,
        choices=FinancialStatusChoices.choices,
    )
    type = models.CharField(
        max_length=32, default=OrderType.REGULAR, choices=OrderType.choices,
    )

    user = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        blank=True,
        null=True,
        related_name="orders",
        on_delete=models.SET_NULL,
    )

    billing_address = models.ForeignKey(
        "addresses.Address",
        related_name="+",
        editable=False,
        null=True,
        on_delete=models.SET_NULL,
    )
    shipping_address = models.ForeignKey(
        "addresses.Address",
        related_name="+",
        editable=False,
        null=True,
        on_delete=models.SET_NULL,
    )

    cancel_reason = models.CharField(
        verbose_name=_("Cancel Reason"),
        max_length=100,
        choices=CancelReasonChoices.choices,
        blank=True,
        help_text=_("The reason why the order was canceled."),
    )
    cancelled_at = models.DateTimeField(
        verbose_name=_("Canceled at"),
        blank=True,
        null=True,
        help_text=_("The date and time when the order was canceled."),
    )
    closed_at = models.DateTimeField(
        verbose_name=_("Closed at"),
        blank=True,
        null=True,
        help_text=_("The date and time when the order was closed."),
    )
    metadata = models.JSONField(default=dict, blank=True)

    class Meta:
        verbose_name = _("Order")
        verbose_name_plural = _("Orders")

    @property
    def fully_allocated(self):
        fully_allocated = [True if item.fully_allocated else False for item in self.lines.all()]
        return all(fully_allocated)


class LineItem(index.Indexed, Orderable, BaseModel):
    """ """

    order = ParentalKey(Order, related_name="lines", on_delete=models.CASCADE)
    variant = models.ForeignKey(
        "products.ProductVariant",
        related_name="order_lines",
        on_delete=models.SET_NULL,
        blank=True,
        null=True,
    )
    is_shipping_required = models.BooleanField()
    quantity = models.IntegerField(validators=[MinValueValidator(1)])
    quantity_fulfilled = models.IntegerField(
        validators=[MinValueValidator(0)], default=0
    )
    purchase_order = models.ForeignKey(
        "purchases.PurchaseOrderItem",
        related_name="sales_orders",
        on_delete=models.SET_NULL,
        null=True,
    )
    metadata = models.JSONField(default=dict, blank=True)

    @property
    def quantity_unfulfilled(self):
        return self.quantity - self.quantity_fulfilled

    @property
    def unallocated_quantity(self):
        return self.quantity - self.allocated

    @property
    def allocated(self):
        return self.allocations.aggregate(allocated=Sum("quantity_allocated"))["allocated"] or 0

    @property
    def fully_allocated(self):
        return self.allocated == self.quantity

    @property
    def requires(self):
        return self.quantity - self.allocated["allocated"]

    def __str__(self):
        return f"Order: #{self.order.number} | Variant: {self.variant.name} | Quantity: {self.quantity_unfulfilled}"


class BatchOrderUpload(index.Indexed, Orderable, BaseModel):

    order = ParentalKey(
        Order, related_name="batches", on_delete=models.CASCADE, null=True
    )
    orders = StreamField(
        [
            (
                "upload",
                TableBlock(
                    table_options={
                        "minSpareRows": 0,
                        "startRows": 1,
                        "startCols": 9,
                        "colHeaders": True,
                        "rowHeaders": False,
                        "contextMenu": True,
                        "editor": "text",
                        "stretchH": "all",
                        "height": 216,
                        "language": "en",
                        "renderer": "text",
                        "autoColumnSize": False,
                    }
                ),
            )
        ]
    )

    class Meta:
        verbose_name = _("Batch Order Upload")
        verbose_name_plural = _("Batch Orders Upload")

    def clean(self):
        for data in self.orders.stream_data:
            field, values, opts = data
            print(opts)
            rows = values.get("data")
            iterator = iter(rows)
            is_first_row_headers = values.get("first_row_is_table_header")
            if is_first_row_headers:
                next(iterator)
            keys = [
                "link",
                "product",
                "quantity",
                "price",
                "paid",
                "total_price",
                "date",
            ]
            for row in rows:
                line_item = dict(zip(keys, row))
                if None in line_item.values():
                    raise ValidationError(_("Data is not good"))
                LineItem.objects.create(**line_item)

    def save(self, **kwargs):
        self.clean()
        if not self.order:
            order = Order.objects.create(
                number=get_next_value("order_number", initial_value=10000)
            )
            self.order = order

assistant/weblink_channel/templates/weblink_channel/orders/detail.html
{% extends 'weblink_channel/base.html' %} 
{% load i18n %} 
{% block body %}


<div class="flex justify-center my-6">
  <div class="flex flex-col w-full p-8 text-gray-800 bg-white shadow-lg pin-r pin-y md:w-4/5 lg:w-4/5">
    <nav class="text-black font-bold my-8" aria-label="Breadcrumb">
        <ol class="list-none p-0 inline-flex">
            <li class="flex items-center">
                <a href="{% url 'weblink_channel:customer_order_list' %}">Orders</a>
                <svg class="fill-current w-3 h-3 mx-3" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 320 512">
                    <path d="M285.476 272.971L91.132 467.314c-9.373 9.373-24.569 9.373-33.941 0l-22.667-22.667c-9.357-9.357-9.375-24.522-.04-33.901L188.505 256 34.484 101.255c-9.335-9.379-9.317-24.544.04-33.901l22.667-22.667c9.373-9.373 24.569-9.373 33.941 0L285.475 239.03c9.373 9.372 9.373 24.568.001 33.941z"/>
                </svg>
            </li>
            <li>
                <a href="{ url 'weblink_channel:customer_order_detail' order.guid %}">#{{ order.number }}</a>
            </li>
        </ol>
    </nav>
    <div class="flex-1">
      <table class="w-full text-sm lg:text-base" cellspacing="0">
        <thead>
          <tr class="h-12 uppercase">
            <th class="text-left">Product</th>
            <th class="lg:text-right text-left pl-5 lg:pl-0">
              <span class="lg:hidden" title="Quantity">Qtd</span>
              <span class="hidden lg:inline">Quantity</span>
            </th>
            <th class="hidden text-right md:table-cell">price</th>
            
          </tr>
        </thead>
        <tbody>
          {% for line in order.lines.all %}
          <tr>
            <td>
              <a href="#">
                <p class="mb-2 md:ml-4">{{ line.variant.name }}</p>
              </a>
            </td>
            <td class="justify-center md:justify-end md:flex mt-6">
              <div class="w-20 h-10">
                {{ line.quantity }}
              </div>
            </td>
            <td class="hidden text-right md:table-cell">
              <span class="text-sm lg:text-base font-medium">
                {{ line.variant.price }}
              </span>
            </td>
          </tr>
          {% endfor %}
        </tbody>
      </table>
      <hr class="pb-6 mt-6" />
      <div class="my-4 mt-6 -mx-2 lg:flex">
        <div class="lg:px-2 lg:w-1/2">
          <div class="p-4 bg-gray-100 rounded-full">
            <h1 class="ml-2 font-bold uppercase">Order Details</h1>
          </div>
          <div class="p-4">
            <div class="flex justify-between border-b">
              <div class="lg:px-4 lg:py-2 m-2 text-lg lg:text-xl font-bold text-center text-gray-800">
                Total
              </div>
              <div class="lg:px-4 lg:py-2 m-2 lg:text-lg font-bold text-center text-gray-900">
                {{ order.total_price }}
              </div>
            </div>
            <div class="flex justify-between pt-4 border-b">
              <div class="lg:px-4 lg:py-2 m-2 text-lg lg:text-xl font-bold text-center text-gray-800">
                Subtotal
              </div>
              <div class="lg:px-4 lg:py-2 m-2 lg:text-lg font-bold text-center text-gray-900">
                {{ order.subtotal_price }}
              </div>
            </div>
            <div class="flex justify-between pt-4 border-b">
              <div class="lg:px-4 lg:py-2 m-2 text-lg lg:text-xl font-bold text-center text-gray-800">
                Payment Status
              </div>
              <div class="lg:px-4 lg:py-2 m-2 lg:text-lg font-bold text-center text-gray-900">
                {{ order.financial_status }}
              </div>
            </div>
          </div>
        </div>

        <div class="lg:px-2 lg:w-1/2">
            <div class="p-4 bg-gray-100 rounded-full">
            <h1 class="ml-2 font-bold uppercase">Shipping Details</h1>
            </div>
            <div class="p-4">
            <p class="mb-6 italic">Shipping and additional costs are calculated based on values you have entered</p>
            <div class="flex justify-between border-b">
                <div class="lg:px-4 lg:py-2 m-2 text-lg lg:text-xl font-bold text-center text-gray-800">
                Country
                </div>
                <div class="lg:px-4 lg:py-2 m-2 lg:text-lg font-bold text-center text-gray-900">
                {{ order.shipping_address.country }}
                </div>
            </div>
            <div class="flex justify-between pt-4 border-b">
                <div class="lg:px-4 lg:py-2 m-2 text-lg lg:text-xl font-bold text-center text-gray-800">
                State
                </div>
                <div class="lg:px-4 lg:py-2 m-2 lg:text-lg font-bold text-center text-gray-900">
                {{ order.shipping_address.city_area }}
                </div>
            </div>
            <div class="flex justify-between pt-4 border-b">
                <div class="lg:px-4 lg:py-2 m-2 text-lg lg:text-xl font-bold text-center text-gray-800">
                City
                </div>
                <div class="lg:px-4 lg:py-2 m-2 lg:text-lg font-bold text-center text-gray-900">
                {{ order.shipping_address.city }}
                </div>
            </div>
            <div class="flex justify-between pt-4 border-b">
                <div class="lg:px-4 lg:py-2 m-2 text-lg lg:text-xl font-bold text-center text-gray-800">
                Postal Code
                </div>
                <div class="lg:px-4 lg:py-2 m-2 lg:text-lg font-bold text-center text-gray-900">
                {{ order.shipping_address.postal_code }}
                </div>
            </div>
            </div>
        </div>
      </div>
    </div>
  </div>
</div>
{% endblock body %}

assistant/weblink_channel/templates/weblink_channel/orders/form.html
{% extends 'weblink_channel/base.html' %} 
{% load i18n static %} 
{% block body %}
<div id="app" class="bg-gray-200 my-6 font-mono my-16">
    <form method="POST" action="{% url 'weblink_channel:checkout' %}" novalidate="true">
        {% csrf_token %}
        <p v-if="errors.length">
            <b>Please correct the following error(s):</b>
            <ul>
            <li v-for="error in errors">{{ error }}</li>
            </ul>
        </p>

        <div class="container mx-auto flex justify-between">
            <div class="w-2/6">
                <div class="shadow-xl rounded-lg py-16 px-12 mx-2 bg-white">
                    <h1 class="font-semibold text-3xl">{% trans 'Your Information:' %}</h1>
                    {% include 'pages/checkout/form.html' with form=customer_form %}
                    {% include 'pages/checkout/form.html' with form=shipping_form %}
                </div>
            </div>
            <div class="w-4/6">
                <div class="shadow-xl rounded-lg py-16 px-12 mx-2 bg-white">
                    <h1 class="font-semibold text-3xl">{% trans 'Products Information' %}</h1>
                    {{ product_add_formset.management_form }}
                    {% for form in product_add_formset %}
                    <div class="formset-form" v-for="(item, index) in form.product_add_formset" :key="index">
                        {% include 'pages/checkout/form.html' with form=form %}
                        <button @click="removeProduct" class="mt-3 text-pink-500 bg-transparent border border-solid border-pink-500 hover:bg-pink-500 hover:text-white active:bg-pink-600 font-bold uppercase text-xs px-4 py-2 rounded outline-none focus:outline-none mr-1 mb-1" type="button">{% trans 'Remove this product' %}</button>
                    </div>
                    {% endfor %}
                    <div class="flex justify-end">
                        <button @click="addProduct" class="text-indigo-500 bg-transparent border border-solid border-indigo-500 hover:bg-indigo-500 hover:text-white active:bg-indigo-600 font-bold uppercase text-xs px-4 py-2 rounded outline-none focus:outline-none mr-1 mb-1" type="button">{% trans 'Add Another Product' %}</button>
                    </div>
                    <div class="flex justify-end">
                        <button @click.prevent="checkout" class="mt-5 bg-indigo-500 text-white active:bg-indigo-600 font-bold uppercase text-sm px-6 py-3 rounded shadow hover:shadow-lg outline-none focus:outline-none mr-1 mb-1" type="submit">{% trans 'Submit Order Request' %}</button>
                    </div>
                </div>
            </div>
        </div>
    </form>
</div>
{{ user.shipping_address.state}}
{% endblock body %} 
{% block vue_app %}
<script>
    const http = axios.create({
      timeout: 1000,
      headers: {'X-CSRFTOKEN': '{{ csrf_token }}'}
    });
    const csrfToken = "{{ csrf_token }}";
    const checkoutURL = "{% url 'weblink_channel:checkout' %}"
    const successURL = "{% url 'weblink_channel:customer_order_list' %}"
    const checkout = "{% url 'weblink_channel:checkout' %}"
    const checkoutAPI = "{% url 'weblink_channel:checkout-api-view' %}"
    {% if user.is_authenticated %}
        const customer = {
            name: "{{ user.shipping_address.full_name|safe }}",
            email: "{{ user.email|safe }}",
            city: "{{ user.shipping_address.city|safe }}",
            city_area: "{{ user.shipping_address.city_area|safe }}",
            postal_code: "{{ user.shipping_address.postal_code|safe }}"
        };
        {% else %}
        const customer = {
            name: "",
            email: "",
            city: "",
            state: "",
            postal_code: ""
        }
    {% endif %}
  </script>
  <script src="{% static 'js/checkout.js' %}"></script>
{% endblock vue_app %}

assistant/weblink_channel/templates/weblink_channel/orders/list.html
{% extends 'weblink_channel/base.html' %} 
{% load i18n %} 
{% block body %}
    <div class="md:w-4/5 lg:w-4/5 mx-auto px-4">
        <div class="py-8">
            <div>
                <h2 class="text-2xl font-semibold leading-tight">Orders</h2>
            </div>
            <div class="my-2 flex sm:flex-row flex-col">
                <div class="flex flex-row mb-1 sm:mb-0">
                    <div class="relative">
                        <select
                            class="appearance-none h-full rounded-r border-t sm:rounded-r-none sm:border-r-0 border-r border-b block appearance-none w-full bg-white border-gray-400 text-gray-700 py-2 px-4 pr-8 leading-tight focus:outline-none focus:border-l focus:border-r focus:bg-white focus:border-gray-500">
                            <option>All</option>
                            <option>Active</option>
                            <option>Inactive</option>
                        </select>
                        <div
                            class="pointer-events-none absolute inset-y-0 right-0 flex items-center px-2 text-gray-700">
                            <svg class="fill-current h-4 w-4" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20">
                                <path d="M9.293 12.95l.707.707L15.657 8l-1.414-1.414L10 10.828 5.757 6.586 4.343 8z" />
                            </svg>
                        </div>
                    </div>
                </div>
                <div class="block relative">
                    <span class="h-full absolute inset-y-0 left-0 flex items-center pl-2">
                        <svg viewBox="0 0 24 24" class="h-4 w-4 fill-current text-gray-500">
                            <path
                                d="M10 4a6 6 0 100 12 6 6 0 000-12zm-8 6a8 8 0 1114.32 4.906l5.387 5.387a1 1 0 01-1.414 1.414l-5.387-5.387A8 8 0 012 10z">
                            </path>
                        </svg>
                    </span>
                    <input placeholder="Search"
                        class="appearance-none rounded-r rounded-l sm:rounded-l-none border border-gray-400 border-b block pl-8 pr-6 py-2 w-full bg-white text-sm placeholder-gray-400 text-gray-700 focus:bg-white focus:placeholder-gray-600 focus:text-gray-700 focus:outline-none" />
                </div>

                <div class="flex justify-end">
                    <a class="appearance-none bg-gray-200 text-green-900 px-2 py-1 shadow-sm border border-green-400 rounded-md mr-3" href="{% url 'weblink_channel:customer_order_create' %}">New Order</a>
                </div>
            </div>
            <div class="-mx-4 sm:-mx-8 px-4 sm:px-8 py-4 overflow-x-auto">
                <div class="inline-block min-w-full shadow rounded-lg overflow-hidden">
                    <table class="min-w-full leading-normal">
                        <thead>
                            <tr>
                                <th
                                    class="px-5 py-3 border-b-2 border-gray-200 bg-gray-100 text-left text-xs font-semibold text-gray-600 uppercase tracking-wider">
                                    Number
                                </th>
                                <th
                                    class="px-5 py-3 border-b-2 border-gray-200 bg-gray-100 text-left text-xs font-semibold text-gray-600 uppercase tracking-wider">
                                    Status
                                </th>
                                <th
                                    class="px-5 py-3 border-b-2 border-gray-200 bg-gray-100 text-left text-xs font-semibold text-gray-600 uppercase tracking-wider">
                                    Actions
                                </th>
                            </tr>
                        </thead>
                        <tbody>
                            {% for order in orders %}
                            <tr>
                                <td class="px-5 py-5 border-b border-gray-200 bg-white text-sm">
                                    <div class="flex items-center">
                                        <p class="text-gray-900 whitespace-no-wrap">
                                            {{ order.number }}
                                        </p>
                                    </div>
                                </td>
                                <td class="px-5 py-5 border-b border-gray-200 bg-white text-sm">
                                    <span
                                        class="relative inline-block px-3 py-1 font-semibold text-green-900 leading-tight">
                                        <span aria-hidden
                                            class="absolute inset-0 bg-green-200 opacity-50 rounded-full"></span>
                                        <span class="relative">{{ order.get_status_display }}</span>
                                    </span>
                                </td>
                                <td class="px-5 py-5 border-b border-gray-200 bg-white text-sm">
                                    <a href="{% url 'weblink_channel:customer_order_detail' order.guid %}">View</button>
                                </td>
                            </tr>
                            {% endfor %}
                        </tbody>
                    </table>
                    <div
                        class="px-5 py-5 bg-white border-t flex flex-col xs:flex-row items-center xs:justify-between          ">
                        <span class="text-xs xs:text-sm text-gray-900">
                            Showing 1 to 4 of 50 Entries
                        </span>
                        <div class="inline-flex mt-2 xs:mt-0">
                            <button
                                class="text-sm bg-gray-300 hover:bg-gray-400 text-gray-800 font-semibold py-2 px-4 rounded-l">
                                Prev
                            </button>
                            <button
                                class="text-sm bg-gray-300 hover:bg-gray-400 text-gray-800 font-semibold py-2 px-4 rounded-r">
                                Next
                            </button>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock body %}