assistant/api/urls.py
from django.urls import include, path

app_name = "api"

urlpatterns = [
    path("v1/", include("assistant.api.v1.urls", namespace="v1"))
]

assistant/orders/urls.py
from django.urls import path

from .views import OrderListView, order_search, add_to_purchase_modal

app_name = "orders"

urlpatterns = [
    path("", OrderListView.as_view(), name="order-list"),
    path('search/', order_search, name="order-search"),
    path(
        "add-to-purchase-modal/<uuid:guid>/",
        add_to_purchase_modal,
        name="add_to_purchase_modal",
    ),
]

assistant/pages/urls.py
from django.urls import path

from .views import test

app_name = "pages"

urlpatterns = [path("test/", test, name="test")]

assistant/products/urls.py
from django.urls import path

from .views import (
    product_orders_modal,
    make_product_purchase,
    allocate_product_to_order,
    receive_product_stock,
    ProductListView,
    product_add_to_purchase,
    product_search,
)

app_name = "products"

urlpatterns = [
    path('', ProductListView.as_view(), name="product-list"),
    path('search/', product_search, name="product-search"),
    path(
        'add-to-purchase/<uuid:guid>/',
        product_add_to_purchase,
        name="product-add-to-purchase",
    ),
    path(
        "product-orders-modal/<uuid:guid>/",
        product_orders_modal,
        name="product_orders_modal_workflow",
    ),
    path(
        "products/make-purchase/<uuid:guid>",
        make_product_purchase,
        name="make_product_purchase",
    ),
    path(
        "products/allocation/<uuid:guid>/",
        allocate_product_to_order,
        name="allocate_product_to_order",
    ),
    path(
        "products/receive/<uuid:guid>/",
        receive_product_stock,
        name="receive_product_stock",
    ),
]

assistant/purchases/urls.py
from django.urls import path
from .views import PurchaseListView, recieve_item

app_name = "purchases"

urlpatterns = [
    path("", PurchaseListView.as_view(), name="purchase-order-list"),
    path("<uuid:guid>/", recieve_item, name="receive-item"),
]

assistant/shipping/urls.py
from django.urls import path

from .views import ShipmentListView, ShipmentDetailView, get_dhl_rate, shipping_item_detail_modal

app_name = "shipping"

urlpatterns = [
    path("", ShipmentListView.as_view(), name="shipment_list"),
    path("<uuid:guid>/", ShipmentDetailView.as_view(), name="shipment_detail"),
    path("modal/<uuid:guid>/", shipping_item_detail_modal, name="shipping_item_detail_modal"),
    path("rates/hdl/", get_dhl_rate, name="get_dhl_rate"),
]

assistant/users/urls.py
from django.urls import path

from assistant.users.views import (
    user_detail_view,
    user_redirect_view,
    user_update_view,
    user_email_exists,
)

app_name = "users"
urlpatterns = [
    path("~redirect/", view=user_redirect_view, name="redirect"),
    path("~update/", view=user_update_view, name="update"),
    path("<str:username>/", view=user_detail_view, name="detail"),
    path("exists/<str:email>", user_email_exists, name="user_email_exists"),
]

config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.urls import include, path
from django.views import defaults as default_views
from django.views.generic import TemplateView
from rest_framework.authtoken.views import obtain_auth_token

from wagtail.core import urls as wagtail_urls
from wagtail.admin import urls as wagtailadmin_urls
from wagtail.documents import urls as wagtaildocs_urls

urlpatterns = [
    # Django Admin, use {% url 'admin:index' %}
    path(settings.ADMIN_URL, admin.site.urls),
    # User management
    path("users/", include("assistant.users.urls", namespace="users")),
    path("ht/", include("health_check.urls")),
    path("accounts/", include("allauth.urls")),
    # Wagtail Admin
    path("cms/", include(wagtailadmin_urls)),
    path("documents/", include(wagtaildocs_urls)),
    # Your stuff: custom urls includes go here
    path("pages/", include("assistant.pages.urls", namespace="pages")),
    path("products/", include("assistant.products.urls", namespace="products")),
    path("purchases/", include("assistant.purchases.urls", namespace="purchases")),
    path("orders/", include("assistant.orders.urls", namespace="orders")),
    path("warehouse/", include("assistant.warehouse.urls", namespace="warehouse")),
    path("shipping/", include("assistant.shipping.urls", namespace="shipping")),
    path(
        "weblink-channel/",
        include("assistant.weblink_channel.urls", namespace="weblink_channel"),
    ),
    path("shopify/", include("assistant.shopify_sync.urls"), name="shopify_sync"),
    path("api/", include("config.api_router")),
    path("auth-token/", obtain_auth_token),
    # Wagtail CMS
    path("", include(wagtail_urls)),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
if settings.DEBUG:
    # Static file serving when using Gunicorn + Uvicorn for local web socket development
    urlpatterns += staticfiles_urlpatterns()

# API URLS
# urlpatterns += [
#     # API base url
#     path("api/", include("config.api_router")),
#     # DRF auth token
#     path("auth-token/", obtain_auth_token),
#     # Wagtail CMS
#     path('', include(wagtail_urls)),
# ]

if settings.USE_SILK:
    urlpatterns += [path("silk/", include("silk.urls", namespace="silk"))]

if settings.DEBUG:
    # This allows the error pages to be debugged during development, just visit
    # these url in browser to see how these error pages look like.
    urlpatterns += [
        path(
            "400/",
            default_views.bad_request,
            kwargs={"exception": Exception("Bad Request!")},
        ),
        path(
            "403/",
            default_views.permission_denied,
            kwargs={"exception": Exception("Permission Denied")},
        ),
        path(
            "404/",
            default_views.page_not_found,
            kwargs={"exception": Exception("Page not Found")},
        ),
        path("500/", default_views.server_error),
    ]
    if "debug_toolbar" in settings.INSTALLED_APPS:
        import debug_toolbar

        urlpatterns = [path("__debug__/", include(debug_toolbar.urls))] + urlpatterns

assistant/api/models.py
from django.db import models

# Create your models here.

assistant/users/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from django.db.models import CharField
from django.urls import reverse
from django.core.exceptions import ValidationError
from django.utils.translation import gettext_lazy as _

from assistant.core.models import BaseModel


class User(AbstractUser):
    """Default user for assistant.
    """

    #: First and last name do not cover name patterns around the globe
    name = CharField(_("Name of User"), blank=True, max_length=255)

    shipping_address = models.ForeignKey(
        "addresses.Address",
        related_name="+",
        null=True,
        blank=True,
        on_delete=models.SET_NULL,
    )
    billing_address = models.ForeignKey(
        "addresses.Address",
        related_name="+",
        null=True,
        blank=True,
        on_delete=models.SET_NULL,
    )

    @property
    def fullname(self):
        return self.name or self.email

    def get_absolute_url(self):
        """Get url for user's detail view.

        Returns:
            str: URL for user detail.

        """
        return reverse("users:detail", kwargs={"username": self.username})

assistant/webhooks/models.py
from django.db import models

# Create your models here.

assistant/whatsapp_channel/models.py
from django.db import models

# Create your models here.

assistant/products/forms.py
import logging

from django import forms
from django.utils.translation import ugettext_lazy as _

from assistant.products.models import Supplier
from assistant.weblink_channel.models import PurchaseOrder, PurchaseOrderItem
from assistant.orders.models import Order, LineItem

from .services import process_add_to_purchase_order, process_purchase_order

logger = logging.getLogger(__name__)


class PurchaseOrderAddForm(forms.Form):
    purchase_order = forms.UUIDField()
    add_type = forms.CharField()

    def save(self, item: LineItem):
        obj = process_add_to_purchase_order(item=item, **self.cleaned_data)
        return obj

    def clean_purchase_order(self):
        data = self.cleaned_data["purchase_order"]
        if not PurchaseOrder.objects.filter(guid=data).exists():
            raise forms.ValidationError(
                _("Invalid value: The PurchaseOrder Doesn't Exists"), code="invalid",
            )
        return data


class PurchaseOrderForm(forms.Form):
    supplier = forms.CharField(label=_("Supplier"), required=False)
    system_supplier = forms.ModelChoiceField(
        label=_("Supplier"), queryset=Supplier.objects.all(), required=False
    )
    estimated_arrival = forms.IntegerField()
    quantity = forms.IntegerField()

    def save(self, item: LineItem):
        obj = process_purchase_order(item=item, **self.cleaned_data)
        return obj

    def clean(self):
        cleaned_data = super().clean()
        if not cleaned_data.get("system_supplier") and not cleaned_data.get("supplier"):
            raise forms.ValidationError(
                _("Invalid value: One of the Supplier Fields should be provided"),
                code="invalid",
            )


class AllocationForm(forms.Form):
    def __init__(self, *args, **kwargs):
        variant = kwargs.pop("variant")
        super().__init__(*args, **kwargs)
        self.fields["orders"].queryset = LineItem.objects.exclude(
            models.Q(
                order__status__in=[
                    Order.StatusChoices.FULFILLED,
                    Order.StatusChoices.CANCELED,
                ]
            ),
            models.Q(variant=variant),
        )

    orders = forms.ModelMultipleChoiceField(queryset=LineItem.objects.none())

assistant/purchases/forms.py
import logging

from django import forms
from django.db import models
from django.utils.translation import ugettext_lazy as _

from assistant.products.models import Supplier
from assistant.orders.models import Order, LineItem
from .models import PurchaseOrder

from assistant.purchases.services import (
    process_add_to_purchase_order,
    process_purchase_order,
    receive_stock,
)

logger = logging.getLogger(__name__)


class PurchaseOrderForm(forms.Form):
    def __init__(self, *args, **kwargs):
        self.variant = kwargs.pop("variant")
        super().__init__(**kwargs)

    supplier = forms.CharField(
        label=_("New Supplier"),
        required=False,
        widget=forms.TextInput(attrs={'class': 'form-control'}),
    )
    system_supplier = forms.ModelChoiceField(
        label=_("Existing Supplier"),
        queryset=Supplier.objects.all(),
        required=False,
        widget=forms.Select(attrs={'class': 'form-control'}),
    )
    estimated_arrival = forms.IntegerField(
        widget=forms.NumberInput(attrs={'class': 'form-control'})
    )
    quantity = forms.IntegerField(
        widget=forms.NumberInput(attrs={'class': 'form-control'})
    )
    purchase_order = forms.ModelChoiceField(
        label=_("Purchase Order"),
        queryset=PurchaseOrder.objects.all(),
        required=False,
        widget=forms.Select(attrs={'class': 'form-control'}),
    )

    def save(self):
        if self.cleaned_data["purchase_order"]:
            obj = process_add_to_purchase_order(
                variant=self.variant, **self.cleaned_data
            )
        else:
            obj = process_purchase_order(
                variant=self.variant, **self.cleaned_data
            )
        return obj

    def clean(self):
        cleaned_data = super().clean()
        if not cleaned_data.get("system_supplier") and not cleaned_data.get(
            "supplier"
        ):
            raise forms.ValidationError(
                _(
                    "Invalid value: One of the Supplier Fields should be provided"
                ),
                code="invalid",
            )


class ReceiveItemForm(forms.Form):
    def __init__(self, *args, **kwargs):
        self.item = kwargs.pop("item")
        super().__init__(**kwargs)

    quantity = forms.IntegerField()

    def save(self):
        item = receive_stock(
            item=self.item, quantity=self.cleaned_data['quantity']
        )
        return item

assistant/shipping/forms.py
from django import forms
from django.contrib.auth import get_user_model
from django.forms import formset_factory

from .models import ShipmentLine, ShipmentPiece, ShippingMethod
from assistant.orders.models import LineItem

User = get_user_model()

class ShipmentForm(forms.Form):

    def __init__(self, *args, **kwargs):
        self.order = kwargs.pop('order')
        super().__init__(*args, **kwargs)

    shipping_method = forms.ModelChoiceField(queryset=ShippingMethod.objects.all())
    shipper = forms.ModelChoiceField(queryset=User.objects.all())


class ShipmentLineDetailForm(forms.Form):

    def __init__(self, *args, **kwargs):
        self.item = kwargs.pop('item')
        super().__init__(*args, **kwargs)
        self.fields['item'].queryset = ShipmentLine.objects.filter(guid=self.item.guid)
    
    item = forms.ModelChoiceField(queryset=ShipmentLine.objects.all(), widget=forms.HiddenInput())
    weight = forms.CharField(widget=forms.NumberInput(attrs={'class': 'form-control'}))
    width = forms.CharField(widget=forms.NumberInput(attrs={'class': 'form-control'}))
    height = forms.CharField(widget=forms.NumberInput(attrs={'class': 'form-control'}))
    depth = forms.CharField(widget=forms.NumberInput(attrs={'class': 'form-control'}))
    declared_value = forms.CharField(widget=forms.NumberInput(attrs={'class': 'form-control'}))

    def save(self):
        order_line_item = LineItem.objects.get(guid=self.item.order_line.guid)
        variant = order_line_item.variant
        variant.weight = self.cleaned_data["weight"]
        variant.width = self.cleaned_data["width"]
        variant.height = self.cleaned_data["height"]
        variant.depth = self.cleaned_data["depth"]
        variant.declared_value = self.cleaned_data["depth"]
        variant.save()


class PieceForm(forms.Form):
    pass

assistant/users/forms.py
from django.contrib.auth import forms, get_user_model
from django.core.exceptions import ValidationError
from django.utils.translation import gettext_lazy as _

User = get_user_model()


class UserChangeForm(forms.UserChangeForm):
    class Meta(forms.UserChangeForm.Meta):
        model = User


class UserCreationForm(forms.UserCreationForm):

    error_message = forms.UserCreationForm.error_messages.update(
        {"duplicate_username": _("This username has already been taken.")}
    )

    class Meta(forms.UserCreationForm.Meta):
        model = User

    def clean_username(self):
        username = self.cleaned_data["username"]

        try:
            User.objects.get(username=username)
        except User.DoesNotExist:
            return username

        raise ValidationError(self.error_messages["duplicate_username"])

assistant/utils/forms.py
from django import forms
from django.utils.translation import gettext_lazy as _
from django.utils.functional import cached_property

TOTAL_FORM_COUNT = "TOTAL_FORMS"
INITIAL_FORM_COUNT = "INITIAL_FORMS"
MIN_NUM_FORM_COUNT = "MIN_NUM_FORMS"
MAX_NUM_FORM_COUNT = "MAX_NUM_FORMS"


class VueManagementForm(forms.Form):
    def __init__(self, *args, **kwargs):
        self.base_fields[TOTAL_FORM_COUNT] = forms.IntegerField(
            widget=forms.HiddenInput(attrs={"v-model": "totalForms"})
        )
        self.base_fields[INITIAL_FORM_COUNT] = forms.IntegerField(
            widget=forms.HiddenInput(attrs={"v-model": "initialForms"})
        )
        self.base_fields[MIN_NUM_FORM_COUNT] = forms.IntegerField(
            required=False, widget=forms.HiddenInput(attrs={"v-model": "minNumForms"}),
        )
        self.base_fields[MAX_NUM_FORM_COUNT] = forms.IntegerField(
            required=False, widget=forms.HiddenInput(attrs={"v-model": "maxNumForms"}),
        )
        super().__init__(*args, **kwargs)


class VueBaseFormSet(forms.BaseFormSet):
    @cached_property
    def management_form(self):
        if self.is_bound:
            form = VueManagementForm(
                self.data, auto_id=self.auto_id, prefix=self.prefix
            )
            if not form.is_valid():
                raise forms.ValidationError(
                    _("ManagementForm data is missing or has been tampered with"),
                    code="missing_management_form",
                )
        else:
            form = VueManagementForm(
                auto_id=self.auto_id,
                prefix=self.prefix,
                initial={
                    TOTAL_FORM_COUNT: self.total_form_count(),
                    INITIAL_FORM_COUNT: self.initial_form_count(),
                    MIN_NUM_FORM_COUNT: self.min_num,
                    MAX_NUM_FORM_COUNT: self.max_num,
                },
            )
        return form

assistant/templates/core/partials/nav.html
<nav class="main-header navbar navbar-expand navbar-white navbar-light">
  <!-- Left navbar links -->
  <ul class="navbar-nav">
    <li class="nav-item">
      <a class="nav-link" data-widget="pushmenu" href="#" role="button"
        ><i class="fas fa-bars"></i
      ></a>
    </li>
    <li class="nav-item d-none d-sm-inline-block">
      <a href="index3.html" class="nav-link">Home</a>
    </li>
    <li class="nav-item d-none d-sm-inline-block">
      <a href="#" class="nav-link">Contact</a>
    </li>
  </ul>

  <!-- SEARCH FORM -->
  <form class="form-inline ml-3">
    <div class="input-group input-group-sm">
      <input
        class="form-control form-control-navbar"
        type="search"
        placeholder="Search"
        aria-label="Search"
      />
      <div class="input-group-append">
        <button class="btn btn-navbar" type="submit">
          <i class="fas fa-search"></i>
        </button>
      </div>
    </div>
  </form>

  <!-- Right navbar links -->
  <ul class="navbar-nav ml-auto">
    <!-- Messages Dropdown Menu -->
    <li class="nav-item dropdown">
      <a class="nav-link" data-toggle="dropdown" href="#">
        <i class="far fa-comments"></i>
        <span class="badge badge-danger navbar-badge">3</span>
      </a>
      <div class="dropdown-menu dropdown-menu-lg dropdown-menu-right">
        <a href="#" class="dropdown-item">
          <!-- Message Start -->
          <div class="media">
            <img
              src="dist/img/user1-128x128.jpg"
              alt="User Avatar"
              class="img-size-50 mr-3 img-circle"
            />
            <div class="media-body">
              <h3 class="dropdown-item-title">
                Brad Diesel
                <span class="float-right text-sm text-danger"
                  ><i class="fas fa-star"></i
                ></span>
              </h3>
              <p class="text-sm">Call me whenever you can...</p>
              <p class="text-sm text-muted">
                <i class="far fa-clock mr-1"></i> 4 Hours Ago
              </p>
            </div>
          </div>
          <!-- Message End -->
        </a>
        <div class="dropdown-divider"></div>
        <a href="#" class="dropdown-item">
          <!-- Message Start -->
          <div class="media">
            <img
              src="dist/img/user8-128x128.jpg"
              alt="User Avatar"
              class="img-size-50 img-circle mr-3"
            />
            <div class="media-body">
              <h3 class="dropdown-item-title">
                John Pierce
                <span class="float-right text-sm text-muted"
                  ><i class="fas fa-star"></i
                ></span>
              </h3>
              <p class="text-sm">I got your message bro</p>
              <p class="text-sm text-muted">
                <i class="far fa-clock mr-1"></i> 4 Hours Ago
              </p>
            </div>
          </div>
          <!-- Message End -->
        </a>
        <div class="dropdown-divider"></div>
        <a href="#" class="dropdown-item">
          <!-- Message Start -->
          <div class="media">
            <img
              src="dist/img/user3-128x128.jpg"
              alt="User Avatar"
              class="img-size-50 img-circle mr-3"
            />
            <div class="media-body">
              <h3 class="dropdown-item-title">
                Nora Silvester
                <span class="float-right text-sm text-warning"
                  ><i class="fas fa-star"></i
                ></span>
              </h3>
              <p class="text-sm">The subject goes here</p>
              <p class="text-sm text-muted">
                <i class="far fa-clock mr-1"></i> 4 Hours Ago
              </p>
            </div>
          </div>
          <!-- Message End -->
        </a>
        <div class="dropdown-divider"></div>
        <a href="#" class="dropdown-item dropdown-footer">See All Messages</a>
      </div>
    </li>
    <!-- Notifications Dropdown Menu -->
    <li class="nav-item dropdown">
      <a class="nav-link" data-toggle="dropdown" href="#">
        <i class="far fa-bell"></i>
        <span class="badge badge-warning navbar-badge">15</span>
      </a>
      <div class="dropdown-menu dropdown-menu-lg dropdown-menu-right">
        <span class="dropdown-header">15 Notifications</span>
        <div class="dropdown-divider"></div>
        <a href="#" class="dropdown-item">
          <i class="fas fa-envelope mr-2"></i> 4 new messages
          <span class="float-right text-muted text-sm">3 mins</span>
        </a>
        <div class="dropdown-divider"></div>
        <a href="#" class="dropdown-item">
          <i class="fas fa-users mr-2"></i> 8 friend requests
          <span class="float-right text-muted text-sm">12 hours</span>
        </a>
        <div class="dropdown-divider"></div>
        <a href="#" class="dropdown-item">
          <i class="fas fa-file mr-2"></i> 3 new reports
          <span class="float-right text-muted text-sm">2 days</span>
        </a>
        <div class="dropdown-divider"></div>
        <a href="#" class="dropdown-item dropdown-footer"
          >See All Notifications</a
        >
      </div>
    </li>
    <li class="nav-item">
      <a
        class="nav-link"
        data-widget="control-sidebar"
        data-slide="true"
        href="#"
        role="button"
        ><i class="fas fa-th-large"></i
      ></a>
    </li>
  </ul>
</nav>

assistant/templates/core/partials/sidebar.html
{% load static i18n %}
<aside class="main-sidebar sidebar-dark-primary elevation-4">
  <!-- Brand Logo -->
  <a href="index3.html" class="brand-link">
    <img
      src="{% static 'images/AdminLTELogo.png' %}"
      alt="{% trans 'Application Logo' %}"
      class="brand-image img-circle elevation-3"
      style="opacity: 0.8"
    />
    <span class="brand-text font-weight-light">Harumio</span>
  </a>

  <!-- Sidebar -->
  <div class="sidebar">
    <!-- Sidebar user panel (optional) -->
    <div class="user-panel mt-3 pb-3 mb-3 d-flex">
      <div class="image">
        <img
          src="{% static 'images/avatar.jpg' %}"
          class="img-circle elevation-2"
          alt="{% trans 'User Image' %}"
        />
      </div>
      <div class="info">
        <a href="#" class="d-block">{{ request.user }}</a>
      </div>
    </div>

    <!-- Sidebar Menu -->
    <nav class="mt-2">
      <ul
        class="nav nav-pills nav-sidebar flex-column"
        data-widget="treeview"
        role="menu"
        data-accordion="false"
      >
        <li class="nav-item">
          <a href="#" class="nav-link">
            <i class="nav-icon fa fa-tachometer-alt"></i>
            <p>{% trans 'Dashboard' %}</p>
          </a>
        </li>
        <li class="nav-item">
          <a href="{% url 'orders:order-list' %}" class="nav-link">
            <i class="nav-icon fa fa-cash-register"></i>
            <p>{% trans 'Sales Orders' %}</p>
          </a>
        </li>
        <li class="nav-item">
          <a href="{% url 'shipping:shipment_list' %}" class="nav-link">
            <i class="nav-icon fa fa-plane-departure"></i>
            <p>{% trans 'Shipping' %}</p>
          </a>
        </li>
        <li class="nav-item has-treeview">
          <a href="#" class="nav-link">
            <i class="nav-icon fa fa-money-bill-alt"></i>
            <p>
              {% trans 'Purchase' %}
              <i class="fas fa-angle-left right"></i>
            </p>
          </a>
          <ul class="nav nav-treeview">
            <li class="nav-item">
              <a href="{% url 'purchases:purchase-order-list' %}" class="nav-link">
                <i class="nav-icon fa fa-copy nav-icon"></i>
                <p>{% trans 'Orders' %}</p>
              </a>
            </li>
            <li class="nav-item">
              <a href="#" class="nav-link">
                <i class="fa fa-box-open nav-icon"></i>
                <p>{% trans 'Receive' %}</p>
              </a>
            </li>
          </ul>
        </li>
        <li class="nav-item has-treeview">
          <a href="#" class="nav-link">
            <i class="nav-icon fa fa-boxes"></i>
            <p>
              {% trans 'Inventory' %}
              <i class="fas fa-angle-left right"></i>
            </p>
          </a>
          <ul class="nav nav-treeview">
            <li class="nav-item">
              <a href="{% url 'products:product-list' %}" class="nav-link">
                <i class="nav-icon fa fa-tshirt"></i>
                <p>{% trans 'Products' %}</p>
              </a>
            </li>
            <li class="nav-item">
              <a href="#" class="nav-link">
                <i class="nav-icon fa fa-barcode"></i>
                <p>{% trans 'SKUs' %}</p>
              </a>
            </li>
          </ul>
        </li>
      </ul>
    </nav>
    <!-- /.sidebar-menu -->
  </div>
  <!-- /.sidebar -->
</aside>