assistant/products/urls.py
from django.urls import path

from .views import (
    product_orders_modal,
    make_product_purchase,
    allocate_product_to_order,
    receive_product_stock,
    ProductListView,
    product_add_to_purchase,
    product_search,
)

app_name = "products"

urlpatterns = [
    path('', ProductListView.as_view(), name="product-list"),
    path('search/', product_search, name="product-search"),
    path(
        'add-to-purchase/<uuid:guid>/',
        product_add_to_purchase,
        name="product-add-to-purchase",
    ),
    path(
        "product-orders-modal/<uuid:guid>/",
        product_orders_modal,
        name="product_orders_modal_workflow",
    ),
    path(
        "products/make-purchase/<uuid:guid>",
        make_product_purchase,
        name="make_product_purchase",
    ),
    path(
        "products/allocation/<uuid:guid>/",
        allocate_product_to_order,
        name="allocate_product_to_order",
    ),
    path(
        "products/receive/<uuid:guid>/",
        receive_product_stock,
        name="receive_product_stock",
    ),
]

assistant/weblink_channel/urls.py
from django.urls import path

from .views import (
    get_product_by_link,
    get_product_by_link_sync,
    checkout,
    CustomerOrderList,
    CustomerOrderDetail,
    CustomerOrderCreate,
    CustomerProductVariantListView,
    CustomerProductVariantDetailView,
    checkout_api_view,
)

app_name = "weblink_channel"

urlpatterns = [
    path("scrape/", get_product_by_link, name="get_product_by_link"),
    path("sync-scrape/", get_product_by_link_sync, name="get_product_by_link_sync",),
    path("checkout/", checkout, name="checkout"),
    path("checkout-api/", checkout_api_view, name="checkout-api-view"),
    path("guest-checkout-api/", checkout_api_view, name="guest-checkout-api-view"),
    path("customer-orders/", CustomerOrderList.as_view(), name="customer_order_list"),
    path(
        "customer-orders/<uuid:guid>/",
        CustomerOrderDetail.as_view(),
        name="customer_order_detail",
    ),
    path(
        "customer-orders/new/",
        CustomerOrderCreate.as_view(),
        name="customer_order_create",
    ),
    path(
        "customer-products/",
        CustomerProductVariantListView.as_view(),
        name="customer_product_list",
    ),
    path(
        "customer-products/<uuid:guid>/",
        CustomerProductVariantDetailView.as_view(),
        name="customer_product_detail",
    ),
]

config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.urls import include, path
from django.views import defaults as default_views
from django.views.generic import TemplateView
from rest_framework.authtoken.views import obtain_auth_token

from wagtail.core import urls as wagtail_urls
from wagtail.admin import urls as wagtailadmin_urls
from wagtail.documents import urls as wagtaildocs_urls

urlpatterns = [
    # Django Admin, use {% url 'admin:index' %}
    path(settings.ADMIN_URL, admin.site.urls),
    # User management
    path("users/", include("assistant.users.urls", namespace="users")),
    path("ht/", include("health_check.urls")),
    path("accounts/", include("allauth.urls")),
    # Wagtail Admin
    path("cms/", include(wagtailadmin_urls)),
    path("documents/", include(wagtaildocs_urls)),
    # Your stuff: custom urls includes go here
    path("pages/", include("assistant.pages.urls", namespace="pages")),
    path("products/", include("assistant.products.urls", namespace="products")),
    path("purchases/", include("assistant.purchases.urls", namespace="purchases")),
    path("orders/", include("assistant.orders.urls", namespace="orders")),
    path("warehouse/", include("assistant.warehouse.urls", namespace="warehouse")),
    path("shipping/", include("assistant.shipping.urls", namespace="shipping")),
    path(
        "weblink-channel/",
        include("assistant.weblink_channel.urls", namespace="weblink_channel"),
    ),
    path("shopify/", include("assistant.shopify_sync.urls"), name="shopify_sync"),
    path("api/", include("config.api_router")),
    path("auth-token/", obtain_auth_token),
    # Wagtail CMS
    path("", include(wagtail_urls)),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
if settings.DEBUG:
    # Static file serving when using Gunicorn + Uvicorn for local web socket development
    urlpatterns += staticfiles_urlpatterns()

# API URLS
# urlpatterns += [
#     # API base url
#     path("api/", include("config.api_router")),
#     # DRF auth token
#     path("auth-token/", obtain_auth_token),
#     # Wagtail CMS
#     path('', include(wagtail_urls)),
# ]

if settings.USE_SILK:
    urlpatterns += [path("silk/", include("silk.urls", namespace="silk"))]

if settings.DEBUG:
    # This allows the error pages to be debugged during development, just visit
    # these url in browser to see how these error pages look like.
    urlpatterns += [
        path(
            "400/",
            default_views.bad_request,
            kwargs={"exception": Exception("Bad Request!")},
        ),
        path(
            "403/",
            default_views.permission_denied,
            kwargs={"exception": Exception("Permission Denied")},
        ),
        path(
            "404/",
            default_views.page_not_found,
            kwargs={"exception": Exception("Page not Found")},
        ),
        path("500/", default_views.server_error),
    ]
    if "debug_toolbar" in settings.INSTALLED_APPS:
        import debug_toolbar

        urlpatterns = [path("__debug__/", include(debug_toolbar.urls))] + urlpatterns

assistant/products/forms.py
import logging

from django import forms
from django.utils.translation import ugettext_lazy as _

from assistant.products.models import Supplier
from assistant.weblink_channel.models import PurchaseOrder, PurchaseOrderItem
from assistant.orders.models import Order, LineItem

from .services import process_add_to_purchase_order, process_purchase_order

logger = logging.getLogger(__name__)


class PurchaseOrderAddForm(forms.Form):
    purchase_order = forms.UUIDField()
    add_type = forms.CharField()

    def save(self, item: LineItem):
        obj = process_add_to_purchase_order(item=item, **self.cleaned_data)
        return obj

    def clean_purchase_order(self):
        data = self.cleaned_data["purchase_order"]
        if not PurchaseOrder.objects.filter(guid=data).exists():
            raise forms.ValidationError(
                _("Invalid value: The PurchaseOrder Doesn't Exists"), code="invalid",
            )
        return data


class PurchaseOrderForm(forms.Form):
    supplier = forms.CharField(label=_("Supplier"), required=False)
    system_supplier = forms.ModelChoiceField(
        label=_("Supplier"), queryset=Supplier.objects.all(), required=False
    )
    estimated_arrival = forms.IntegerField()
    quantity = forms.IntegerField()

    def save(self, item: LineItem):
        obj = process_purchase_order(item=item, **self.cleaned_data)
        return obj

    def clean(self):
        cleaned_data = super().clean()
        if not cleaned_data.get("system_supplier") and not cleaned_data.get("supplier"):
            raise forms.ValidationError(
                _("Invalid value: One of the Supplier Fields should be provided"),
                code="invalid",
            )


class AllocationForm(forms.Form):
    def __init__(self, *args, **kwargs):
        variant = kwargs.pop("variant")
        super().__init__(*args, **kwargs)
        self.fields["orders"].queryset = LineItem.objects.exclude(
            models.Q(
                order__status__in=[
                    Order.StatusChoices.FULFILLED,
                    Order.StatusChoices.CANCELED,
                ]
            ),
            models.Q(variant=variant),
        )

    orders = forms.ModelMultipleChoiceField(queryset=LineItem.objects.none())

assistant/products/views.py
import uuid

from django.core.paginator import Paginator
from django.db.models import F, Q, Sum
from django.http import HttpRequest, JsonResponse, HttpResponse
from django.shortcuts import get_object_or_404, render
from django.views.generic import ListView
from django.utils.translation import gettext_lazy as _
from django.urls import reverse
from django.template.loader import render_to_string
from django.core.paginator import Paginator
from wagtail.admin.modal_workflow import render_modal_workflow

from assistant.orders.models import LineItem, Order
from assistant.products.models import Product, ProductVariant
from assistant.purchases.forms import PurchaseOrderForm
from assistant.purchases.models import PurchaseOrder, PurchaseOrderItem
from assistant.warehouse.forms import SimpleAllocationForm, StockReceiveForm


def product_orders_modal(request, guid: uuid.UUID) -> JsonResponse:
    page_query = int(request.GET.get("page", 1))
    variants = get_object_or_404(Product, guid=guid).variants.all()
    order_lines = LineItem.objects.filter(variant__in=variants)
    qs = Paginator(Order.objects.filter(lines__in=order_lines).distinct(), 2)
    return render_modal_workflow(
        request,
        "products/choosers/orders_list.html",
        None,
        {"paginator": qs, "page": qs.page(page_query), "product_guid": guid,},
        json_data={"step": "chooser"},
    )


def make_product_purchase(
    request: HttpRequest, guid: uuid.UUID
) -> JsonResponse:
    page_query = int(request.GET.get("page", 1))
    variant = ProductVariant.objects.prefetch_related("order_lines").get(
        guid=guid
    )
    purchase_orders = PurchaseOrder.objects.filter(
        status=PurchaseOrder.StatusChoices.DRAFT
    )
    paginator = Paginator(purchase_orders, 5)
    qs = variant.order_lines.aggregate(total_qty=Sum("quantity"))
    if request.method == "POST":
        form = PurchaseOrderForm(data=request.POST, variant=variant)
        if form.is_valid():
            obj = form.save()
            return render_modal_workflow(
                request,
                None,
                None,
                {"obj": obj},
                json_data={"step": "created"},
            )
        return render_modal_workflow(
            request,
            "products/choosers/product_purchase.html",
            None,
            {
                "obj": variant,
                "page": paginator.page(page_query),
                "purchase_orders": purchase_orders,
                "form": form,
                "form_errors": form.errors,
            },
            json_data={"step": "chooser"},
        )
    to_purchase = (
        variant.needed_stock["quantity"]
        or 0 - variant.available_stock["quantity"]
        or 0 - variant.in_purchase["quantity"]
        or 0
    )
    form = PurchaseOrderForm(
        initial={"quantity": to_purchase}, variant=variant
    )
    return render_modal_workflow(
        request,
        "products/choosers/product_purchase.html",
        None,
        {
            "obj": variant,
            "page": paginator.page(page_query),
            "purchase_orders": purchase_orders,
            "form": form,
        },
        json_data={"step": "chooser"},
    )


def allocate_product_to_order(
    request: HttpRequest, guid: uuid.UUID
) -> JsonResponse:
    variant = ProductVariant.objects.prefetch_related("order_lines").get(
        guid=guid
    )
    if request.method == "POST":
        form = SimpleAllocationForm(request.POST, variant=variant)
        if form.is_valid():
            items = form.save()
            return render_modal_workflow(
                request,
                None,
                None,
                {"obj": variant, "assigned_to": items},
                json_data={"step": "allocated"},
            )
    form = SimpleAllocationForm(variant=variant, initial={"variant": variant})
    return render_modal_workflow(
        request,
        "products/choosers/product_allocation.html",
        None,
        {"obj": variant, "form": form},
        json_data={"step": "chooser"},
    )


def receive_product_stock(
    request: HttpRequest, guid: uuid.UUID
) -> JsonResponse:
    variant = ProductVariant.objects.get(guid=guid)
    purchase_orders = PurchaseOrderItem.objects.filter(
        ~Q(
            sales_orders__order__status__in=[
                PurchaseOrderItem.StatusChoices.RECEIVED,
            ]
        ),
        Q(sales_orders__variant=variant),
    )
    if request.method == "POST":
        form = StockReceiveForm(
            request.POST,
            request.FILES,
            variant=variant,
            purchase_orders=purchase_orders,
        )
        if form.is_valid():
            return render_modal_workflow(
                request,
                None,
                None,
                {"obj": variant},
                json_data={"step": "received"},
            )
        return render_modal_workflow(
            request,
            None,
            None,
            {"obj": variant, "form": form},
            json_data={"step": "chooser"},
        )
    form = StockReceiveForm(
        variant=variant,
        purchase_orders=purchase_orders,
        initial={"product_variant": variant},
    )
    return render_modal_workflow(
        request,
        "products/choosers/product_receive.html",
        None,
        {"obj": variant, "form": form},
        json_data={"step": "chooser"},
    )


class ProductListView(ListView):
    template_name = "products/list.html"
    queryset = Product.objects.all().order_by('-created_at')
    context_object_name = "products"
    paginate_by = 10

    def get_queryset(self):
        qs = super().get_queryset().prefetch_related("variants")
        query = self.request.GET.get('q', None)
        if query:
            qs = qs.filter(
                Q(metadata__shopify_id__startswith=query)
                | Q(variants__metadata__shopify_id__startswith=query)
                | Q(title__startswith=query)
            ).order_by('-created_at')
        return qs

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context.update({'q': self.request.GET.get('q', None)})
        return context


def product_search(request: HttpRequest) -> HttpResponse:
    query = request.GET.get('q', None)
    page = request.GET.get('page', None)
    qs = Product.objects.all()
    if query:
        qs = Product.objects.filter(
            Q(metadata__shopify_id__startswith=query)
            | Q(variants__metadata__shopify_id__startswith=query)
            | Q(title__startswith=query)
        ).order_by('-created_at')
    paginator = Paginator(qs, 10)
    if page:
        page_obj = paginator.page(page)
    else:
        page_obj = paginator.page(1)
    context = {
        'products': page_obj.object_list,
        'page_obj': page_obj,
        'q': query,
    }
    return render(request, "products/includes/table_list.html", context)


def product_add_to_purchase(
    request: HttpRequest, guid: uuid.UUID
) -> HttpResponse:
    template_name = "core/modal.html"
    variant = get_object_or_404(ProductVariant, guid=guid)
    context = {
        "title": _("Add To Purchase Order"),
        "action": reverse(
            "products:product-add-to-purchase", kwargs={'guid': variant.guid}
        ),
    }
    if request.method == 'POST':
        form = PurchaseOrderForm(variant=variant, data=request.POST)
        if form.is_valid():
            form.save()
            context.update(
                {'valid': True, 'title': _("Added to Purchase Order")}
            )
            return JsonResponse(context)
        context.update({"valid": False, "form": form})
        return render(request, template_name, context)
    context.update({"form": PurchaseOrderForm(variant=variant)})
    return render(request, template_name, context)

assistant/weblink_channel/templates/weblink_channel/products/detail.html
{% extends 'weblink_channel/base.html' %} 
{% load i18n %} 
{% block body %}

<div class="flex justify-center my-6">
  <div class="flex flex-col w-full p-8 text-gray-800 bg-white shadow-lg pin-r pin-y md:w-4/5 lg:w-4/5">
    <nav class="text-black font-bold my-8" aria-label="Breadcrumb">
        <ol class="list-none p-0 inline-flex">
            <li class="flex items-center">
                <a href="{% url 'weblink_channel:customer_product_list' %}">{% trans 'Products' %}</a>
                <svg class="fill-current w-3 h-3 mx-3" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 320 512">
                    <path d="M285.476 272.971L91.132 467.314c-9.373 9.373-24.569 9.373-33.941 0l-22.667-22.667c-9.357-9.357-9.375-24.522-.04-33.901L188.505 256 34.484 101.255c-9.335-9.379-9.317-24.544.04-33.901l22.667-22.667c9.373-9.373 24.569-9.373 33.941 0L285.475 239.03c9.373 9.372 9.373 24.568.001 33.941z"/>
                </svg>
            </li>
            <li>
                <a href="{ url 'weblink_channel:customer_product_detail' variant.guid %}">#{{ variant.sku }}</a>
            </li>
        </ol>
    </nav>
    <div class="flex-1">
      <div class="my-4 mt-6 -mx-2 lg:flex">
        <div class="lg:px-2 lg:w-1/2">
          <div class="p-4 bg-gray-100 rounded-full">
            <h1 class="ml-2 font-bold uppercase">Product</h1>
          </div>
          <div class="p-4">
            <div class="flex justify-between border-b">
              <div class="lg:px-4 lg:py-2 m-2 text-lg lg:text-xl font-bold text-center text-gray-800">
                Total
              </div>
              <div class="lg:px-4 lg:py-2 m-2 lg:text-lg font-bold text-center text-gray-900">
                {{ variant.name }}
              </div>
            </div>
            <div class="flex justify-between pt-4 border-b">
              <div class="lg:px-4 lg:py-2 m-2 text-lg lg:text-xl font-bold text-center text-gray-800">
                Subtotal
              </div>
              <div class="lg:px-4 lg:py-2 m-2 lg:text-lg font-bold text-center text-gray-900">
                {{ variant.sku }}
              </div>
            </div>
          </div>
        </div>

        <div class="lg:px-2 lg:w-1/2">
            <div class="p-4 bg-gray-100 rounded-full">
            <h1 class="ml-2 font-bold uppercase">Details</h1>
            </div>
            <div class="p-4">
                <div class="flex justify-between border-b">
                    <div class="lg:px-4 lg:py-2 m-2 text-lg lg:text-xl font-bold text-center text-gray-800">
                    Price
                    </div>
                    <div class="lg:px-4 lg:py-2 m-2 lg:text-lg font-bold text-center text-gray-900">
                    {{ variant.price }}
                    </div>
                </div>
                <div class="flex justify-between pt-4 border-b">
                    <div class="lg:px-4 lg:py-2 m-2 text-lg lg:text-xl font-bold text-center text-gray-800">
                    url
                    </div>
                    <div class="lg:px-4 lg:py-2 m-2 lg:text-lg font-bold text-center text-gray-900">
                    {{ variant.metadata.url }}
                    </div>
                </div>
            </div>
        </div>
      </div>
    </div>
  </div>
</div>
{% endblock body %}

assistant/weblink_channel/templates/weblink_channel/products/list.html
{% extends 'weblink_channel/base.html' %} 
{% load i18n %} 
{% block body %}
    <div class="md:w-4/5 lg:w-4/5 mx-auto px-4">
        <div class="py-8">
            <div>
                <h2 class="text-2xl font-semibold leading-tight">{% trans 'Products' %}</h2>
            </div>
            <div class="my-2 flex sm:flex-row flex-col">
                <div class="flex flex-row mb-1 sm:mb-0">
                    <div class="relative">
                        <select
                            class="appearance-none h-full rounded-r border-t sm:rounded-r-none sm:border-r-0 border-r border-b block appearance-none w-full bg-white border-gray-400 text-gray-700 py-2 px-4 pr-8 leading-tight focus:outline-none focus:border-l focus:border-r focus:bg-white focus:border-gray-500">
                            <option>All</option>
                            <option>Active</option>
                            <option>Inactive</option>
                        </select>
                        <div
                            class="pointer-events-none absolute inset-y-0 right-0 flex items-center px-2 text-gray-700">
                            <svg class="fill-current h-4 w-4" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20">
                                <path d="M9.293 12.95l.707.707L15.657 8l-1.414-1.414L10 10.828 5.757 6.586 4.343 8z" />
                            </svg>
                        </div>
                    </div>
                </div>
                <div class="block relative">
                    <span class="h-full absolute inset-y-0 left-0 flex items-center pl-2">
                        <svg viewBox="0 0 24 24" class="h-4 w-4 fill-current text-gray-500">
                            <path
                                d="M10 4a6 6 0 100 12 6 6 0 000-12zm-8 6a8 8 0 1114.32 4.906l5.387 5.387a1 1 0 01-1.414 1.414l-5.387-5.387A8 8 0 012 10z">
                            </path>
                        </svg>
                    </span>
                    <input placeholder="Search"
                        class="appearance-none rounded-r rounded-l sm:rounded-l-none border border-gray-400 border-b block pl-8 pr-6 py-2 w-full bg-white text-sm placeholder-gray-400 text-gray-700 focus:bg-white focus:placeholder-gray-600 focus:text-gray-700 focus:outline-none" />
                </div>

                <div class="flex justify-end">
                    <a class="appearance-none bg-gray-200 text-green-900 px-2 py-1 shadow-sm border border-green-400 rounded-md mr-3" href="{% url 'weblink_channel:customer_order_create' %}">New Order</a>
                </div>
            </div>
            <div class="-mx-4 sm:-mx-8 px-4 sm:px-8 py-4 overflow-x-auto">
                <div class="inline-block min-w-full shadow rounded-lg overflow-hidden">
                    <table class="min-w-full leading-normal">
                        <thead>
                            <tr>
                                <th
                                    class="px-5 py-3 border-b-2 border-gray-200 bg-gray-100 text-left text-xs font-semibold text-gray-600 uppercase tracking-wider">
                                    {% trans 'Number' %}
                                </th>
                                <th
                                    class="px-5 py-3 border-b-2 border-gray-200 bg-gray-100 text-left text-xs font-semibold text-gray-600 uppercase tracking-wider">
                                    {% trans 'Name' %}
                                </th>
                                <th
                                    class="px-5 py-3 border-b-2 border-gray-200 bg-gray-100 text-left text-xs font-semibold text-gray-600 uppercase tracking-wider">
                                    Actions
                                </th>
                            </tr>
                        </thead>
                        <tbody>
                            {% for variant in variants %}
                            <tr>
                                <td class="px-5 py-5 border-b border-gray-200 bg-white text-sm">
                                    <div class="flex items-center">
                                        <p class="text-gray-900 whitespace-no-wrap">
                                            {{ variant.sku }}
                                        </p>
                                    </div>
                                </td>
                                <td class="px-5 py-5 border-b border-gray-200 bg-white text-sm">
                                    <span
                                        class="relative inline-block px-3 py-1 font-semibold text-green-900 leading-tight">
                                        <span aria-hidden
                                            class="absolute inset-0 bg-green-200 opacity-50 rounded-full"></span>
                                        <span class="relative">{{ variant.name }}</span>
                                    </span>
                                </td>
                                <td class="px-5 py-5 border-b border-gray-200 bg-white text-sm">
                                    <a href="{% url 'weblink_channel:customer_product_detail' variant.guid %}">View</button>
                                </td>
                            </tr>
                            {% endfor %}
                        </tbody>
                    </table>
                    <div
                        class="px-5 py-5 bg-white border-t flex flex-col xs:flex-row items-center xs:justify-between">
                        {% include 'pages/components/pagination/number.html' with page=page_obj color=orange %}
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock body %}